### ISSUE TITLE
Use the old 1.10.X branch instead of 1.10.3 stable

### ISSUE THREAD

**Issue by Blisto91** [pythonlover02/Proton-Sarek#6]
Hi there.

Back when dxvk 2.0 was in development a 1.10.x branch was kept for backports to be used in Proton 7 stable releases (with no driver requirement bump). It have a bunch more commits with fixes than 1.10.3 which never got in to a stable dxvk release so it might be worth using that here instead.
The branches in the main dxvk repo got a big cleanup not long ago and so it isn't present there, but i still have it in my own if it could be of interest https://github.com/Blisto91/dxvk/tree/1.10.x

**Comment by Blisto91** [comment]
Ah i missed there is already a PR that mentions it https://github.com/pythonlover02/Proton-Sarek/pull/5

**Comment by pythonlover02** [comment]
> Hi there.
 
> Back when dxvk 2.0 was in development a 1.10.x branch was kept for backports to be used in Proton 7 stable releases (with no driver requirement bump). It have a bunch more commits with fixes than 1.10.3 which never got in to a stable dxvk release so it might be worth using that here instead. The branches in the main dxvk repo got a big cleanup not long ago and so it isn't present there, but i still have it in my own if it could be of interest https://github.com/Blisto91/dxvk/tree/1.10.x

> Ah i missed there is already a PR that mentions it https://github.com/pythonlover02/Proton-Sarek/pull/5

First of all, no problem at all, and thank you for keeping the 1.10.x branch *:)*! I’ve forked it from your repo so that I’ll have a backup just in case. I’m planning to work on it during my vacation when I can really focus as i will have more time. This its because i dont know much about the code of DXVK so i’d like to take that time to learn more about the project understand how it works, do a bit of reverse engineering and hopefully backport some fixes from the newer versions. I’ll also look into adapting the DXVK async patch to make it compatible with this branch.

**Comment by AmerXz** [comment]
I found out that @kevinwidjaja21 has a slightly updated dxvk 1.10.x branch than @Blisto91 

Kevinwidjaja21's dxvk 1.10.x last commit was made on jan 19 2023 

Blisto91's dxvk 1.10.x last commit was made 1 day before kevinwidjaja21's

Also I found on DXVK-macOS fork repo made by @Gcenx has a branch called '1.10.x-old-branch' which has the same last commit as kevinwidjaja21's  on top of that it has other commits made specifically for mac and most importantly it has some other commits for compiling fixes / improvements

Take this as a suggestion because I'm not an expert and I hope this would be useful

**Comment by Blisto91** [comment]
@AmerXz Thank you, yea i see that my branch was 1 commit outdated compared to the original upstream one. I have picked that one in now.

@pythonlover02 I didn't see your edit before now since those don't give a Github notification. I have now included a new commit in my 1.10.x branch that fixes the compilation error. It just needed a couple of extra includes to be able to compile with gcc 13.

**Comment by pythonlover02** [comment]
Thanks for the help, @Blisto91, unfortunately, I'm still encountering some issues during compilation. I downloaded the 1.10.x branch from your repo, but I ran into errors, this time near the end of the compilation process. I’ll attach the log file for reference. It compiles well for you? Maybe i am missing a dependency this time or something

On the other side, the macOS version compiled without any issues. Thanks for the info, @AmerXz 

[logs.txt](https://github.com/user-attachments/files/17759684/logs.txt)

**Comment by AmerXz** [comment]
![Screenshot_2024-11-19_00-01-47](https://github.com/user-attachments/assets/397e44f8-e7f0-4766-93bd-11c4245a5633)

Seems that the latest version of dxvk-macOS is working fine on linux I also tried the previous dxvk-macos because the latest has removed some dlls and the 2 versions of dxvk-macos didn't make a huge performance difference if there wasn't any difference vs dxvk 1.10.3

Note: I only tested one game , so there might be some differences in other games

**Comment by pythonlover02** [comment]
> Seems that the latest version of dxvk-macOS is working fine on linux I also tried the previous dxvk-macos because the latest has removed some dlls and the 2 versions of dxvk-macos didn't make a huge performance difference if there wasn't any difference vs dxvk 1.10.3

Yeah, it's normal. The main differences I observed between the 1.10.3 release and the 1.10.x branch are that the 1.10.x branch includes some per game configurations and various bug fixes. These changes primarily focus on quality of life (QOL) improvements. However, without these settings, certain games either display a black screen or fail to launch altogether.

Additionally, I would like to base the dxvk-Sarek repository on a branch that is as close as possible to the original work. This is important to me because I want to cherry pick which commits to include. I've noticed that some commits on the MacOS branch are specific fixes for MacOS, and there are also some that remove parts of the d3d9 code.

At the end i just want to backport QOL improvements and fixes, as i cant do much more because my limited experience with the dxvk code.

**Comment by pythonlover02** [comment]
> I’ve just pushed a clean branch https://github.com/Gcenx/DXVK-macOS/tree/1.10.x-stock that’s before any modifications/back-ports were added.
> 
> I could cherry pick in the relevant commits to fix building with modern meson/mingw.

I would be very grateful if you could do that. It would make it so much easier. 
Also, if I backport anything that isn’t in your builds, I’ll make sure to let you know *:)*.

**Comment by pythonlover02** [comment]
> Pushed another branch https://github.com/Gcenx/DXVK-macOS/tree/1.10.x-Proton-Sarek
> 
> Heres a build from that branch [dxvk-1.10.x.tar.gz](https://github.com/user-attachments/files/17822529/dxvk-1.10.x.tar.gz) This was build with mingw-64 v12 (gcc14/binutils2.43.1)

> That includes the relevant build fixes plus some other back-ported changes from upstream like removing the incomplete `d3d10.dll` and other slight tweaks like the DXVK-macOS branch just without macOS specific tweaks like relaxing Vulkan requirements etc.

I compiled a version, and everything is working great! Seriously, thank you for all the help. Wishing the best to all of you in life!
I'm closing this issue, and i will be working soon on this, once i end my exams.
